# Generated by Django 3.1.2 on 2020-10-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201012_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='title',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.SlugField(blank=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
    ]
