# Generated by Django 3.1.2 on 2020-10-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title_com',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
    ]
