# Generated by Django 3.1.2 on 2020-10-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0002_auto_20201012_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title_cat',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='title_com',
            new_name='title',
        ),
    ]
