# Generated by Django 3.1.2 on 2020-10-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0004_auto_20201013_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_status',
        ),
        migrations.AddField(
            model_name='company',
            name='company_is_active',
            field=models.BooleanField(default=True, verbose_name='Статус компании'),
        ),
    ]
