# Generated by Django 3.1.2 on 2020-10-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies_app', '0005_auto_20201014_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='title_com',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
